// Code generated by protoc-gen-go.
// source: cfg.proto
// DO NOT EDIT!

/*
Package cfg is a generated protocol buffer package.

It is generated from these files:
	cfg.proto

It has these top-level messages:
	Configuration
*/
package cfg

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Configuration struct {
	DbUser        string `protobuf:"bytes,1,opt,name=db_user" json:"db_user,omitempty"`
	DbServer      string `protobuf:"bytes,2,opt,name=db_server" json:"db_server,omitempty"`
	DbPassword    string `protobuf:"bytes,3,opt,name=db_password" json:"db_password,omitempty"`
	DbDatabase    string `protobuf:"bytes,4,opt,name=db_database" json:"db_database,omitempty"`
	MailAddr      string `protobuf:"bytes,5,opt,name=mail_addr" json:"mail_addr,omitempty"`
	MailPort      int32  `protobuf:"varint,6,opt,name=mail_port" json:"mail_port,omitempty"`
	MailRecipient string `protobuf:"bytes,7,opt,name=mail_recipient" json:"mail_recipient,omitempty"`
	MailSender    string `protobuf:"bytes,8,opt,name=mail_sender" json:"mail_sender,omitempty"`
	MailPassword  string `protobuf:"bytes,9,opt,name=mail_password" json:"mail_password,omitempty"`
	DownloadDir   string `protobuf:"bytes,10,opt,name=download_dir" json:"download_dir,omitempty"`
	PlowdownPath  string `protobuf:"bytes,11,opt,name=plowdown_path" json:"plowdown_path,omitempty"`
	PlowprobePath string `protobuf:"bytes,12,opt,name=plowprobe_path" json:"plowprobe_path,omitempty"`
	HttpPort      int32  `protobuf:"varint,13,opt,name=http_port" json:"http_port,omitempty"`
	BackendPort   int32  `protobuf:"varint,14,opt,name=backend_port" json:"backend_port,omitempty"`
	LinkRegexp    string `protobuf:"bytes,15,opt,name=link_regexp" json:"link_regexp,omitempty"`
	Feed          string `protobuf:"bytes,16,opt,name=feed" json:"feed,omitempty"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}

func init() {
}
