// Code generated by protoc-gen-go.
// source: cfg.proto
// DO NOT EDIT!

/*
Package cfg is a generated protocol buffer package.

It is generated from these files:
	cfg.proto

It has these top-level messages:
	Config
*/
package cfg

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Config struct {
	Db       *Config_Db       `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	Mail     *Config_Mail     `protobuf:"bytes,2,opt,name=mail" json:"mail,omitempty"`
	Download *Config_Download `protobuf:"bytes,3,opt,name=download" json:"download,omitempty"`
	Backend  *Config_Backend  `protobuf:"bytes,4,opt,name=backend" json:"backend,omitempty"`
	Web      *Config_Web      `protobuf:"bytes,5,opt,name=web" json:"web,omitempty"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}

func (m *Config) GetDb() *Config_Db {
	if m != nil {
		return m.Db
	}
	return nil
}

func (m *Config) GetMail() *Config_Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

func (m *Config) GetDownload() *Config_Download {
	if m != nil {
		return m.Download
	}
	return nil
}

func (m *Config) GetBackend() *Config_Backend {
	if m != nil {
		return m.Backend
	}
	return nil
}

func (m *Config) GetWeb() *Config_Web {
	if m != nil {
		return m.Web
	}
	return nil
}

type Config_Db struct {
	User     string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Server   string `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Database string `protobuf:"bytes,4,opt,name=database" json:"database,omitempty"`
}

func (m *Config_Db) Reset()         { *m = Config_Db{} }
func (m *Config_Db) String() string { return proto.CompactTextString(m) }
func (*Config_Db) ProtoMessage()    {}

type Config_Mail struct {
	Addr      string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Port      int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Recipient string `protobuf:"bytes,3,opt,name=recipient" json:"recipient,omitempty"`
	Sender    string `protobuf:"bytes,4,opt,name=sender" json:"sender,omitempty"`
	Password  string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
}

func (m *Config_Mail) Reset()         { *m = Config_Mail{} }
func (m *Config_Mail) String() string { return proto.CompactTextString(m) }
func (*Config_Mail) ProtoMessage()    {}

type Config_Download struct {
	Dir           string `protobuf:"bytes,1,opt,name=dir" json:"dir,omitempty"`
	PlowdownPath  string `protobuf:"bytes,2,opt,name=plowdown_path" json:"plowdown_path,omitempty"`
	PlowprobePath string `protobuf:"bytes,3,opt,name=plowprobe_path" json:"plowprobe_path,omitempty"`
	LinkRegexp    string `protobuf:"bytes,4,opt,name=link_regexp" json:"link_regexp,omitempty"`
	Feed          string `protobuf:"bytes,5,opt,name=feed" json:"feed,omitempty"`
}

func (m *Config_Download) Reset()         { *m = Config_Download{} }
func (m *Config_Download) String() string { return proto.CompactTextString(m) }
func (*Config_Download) ProtoMessage()    {}

type Config_Backend struct {
	Port int32 `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
}

func (m *Config_Backend) Reset()         { *m = Config_Backend{} }
func (m *Config_Backend) String() string { return proto.CompactTextString(m) }
func (*Config_Backend) ProtoMessage()    {}

type Config_Web struct {
	Port int32 `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
}

func (m *Config_Web) Reset()         { *m = Config_Web{} }
func (m *Config_Web) String() string { return proto.CompactTextString(m) }
func (*Config_Web) ProtoMessage()    {}

func init() {
}
